# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GfMoOCN7Zo720RrjE3V7qQkOPFw_d8A
"""

import cv2
import numpy as np
import os
import shutil
import yaml
import glob
import math
from ultralytics import YOLO

# ==========================================
# 1. 경로 설정 및 폴더 초기화
# ==========================================
# 기본 데이터셋 경로 (로컬 폴더 기준)
dataset_base = "./yolo-pose-dataset"

data_pairs = [
    {"colored": f"{dataset_base}/colored/BOX1", "raw": f"{dataset_base}/raw/BOX_1"},
    {"colored": f"{dataset_base}/colored/BOX2", "raw": f"{dataset_base}/raw/BOX_2"},
    {"colored": f"{dataset_base}/colored/BOX3", "raw": f"{dataset_base}/raw/BOX_3"},
    {"colored": f"{dataset_base}/colored/BOX5", "raw": f"{dataset_base}/raw/BOX_5"},
    {"colored": f"{dataset_base}/colored/BOX6", "raw": f"{dataset_base}/raw/BOX_6"}
]

base_dataset_dir = "./datasets_pose"
train_img_dir = os.path.join(base_dataset_dir, "images", "train")
val_img_dir = os.path.join(base_dataset_dir, "images", "val")
train_label_dir = os.path.join(base_dataset_dir, "labels", "train")
val_label_dir = os.path.join(base_dataset_dir, "labels", "val")
debug_dir = "./debug_extraction"

for path in [train_img_dir, val_img_dir, train_label_dir, val_label_dir, debug_dir]:
    if os.path.exists(path): shutil.rmtree(path)
    os.makedirs(path)

# ==========================================
# 2. 극한의 필터링이 적용된 점 찾기 함수
# ==========================================
def get_top_2_centers(mask, is_hinge, img_width):
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    valid_centers = []

    for c in contours:
        area = cv2.contourArea(c)

        if 1 < area < 500:
            M = cv2.moments(c)
            if M["m00"] != 0:
                cx = int(M["m10"] / M["m00"])
                cy = int(M["m01"] / M["m00"])

                if is_hinge and cx < img_width * 0.5:
                    continue

                valid_centers.append((cx, cy, area))

    valid_centers = sorted(valid_centers, key=lambda x: x[2], reverse=True)[:2]
    centers = [(x[0], x[1]) for x in valid_centers]
    return sorted(centers, key=lambda p: p[1]) if len(centers) == 2 else []

# ==========================================
# 3. 데이터 추출 실행
# ==========================================
success_count = 0

for pair in data_pairs:
    colored_dir = pair["colored"]
    raw_dir = pair["raw"]

    if not os.path.exists(colored_dir): continue

    for filename in os.listdir(colored_dir):
        if not filename.lower().endswith((".jpg", ".png")): continue

        file_num_str = filename.split('_')[-1].split('.')[0]
        if file_num_str.isdigit() and int(file_num_str) >= 21:
            curr_img_dir, curr_lbl_dir = val_img_dir, val_label_dir
        else:
            curr_img_dir, curr_lbl_dir = train_img_dir, train_label_dir

        colored_path = os.path.join(colored_dir, filename)
        raw_path = os.path.join(raw_dir, filename)

        if not os.path.exists(raw_path): continue

        img_array = np.fromfile(colored_path, np.uint8)
        image = cv2.imdecode(img_array, cv2.IMREAD_COLOR)
        if image is None: continue

        h, w, _ = image.shape
        hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

        mask_green = cv2.inRange(hsv, np.array([50, 40, 200]), np.array([70, 150, 255]))
        mask_red = cv2.bitwise_or(
            cv2.inRange(hsv, np.array([0, 100, 100]), np.array([10, 255, 255])),
            cv2.inRange(hsv, np.array([170, 100, 100]), np.array([180, 255, 255]))
        )

        green_centers = get_top_2_centers(mask_green, is_hinge=True, img_width=w)
        red_centers = get_top_2_centers(mask_red, is_hinge=False, img_width=w)

        if len(green_centers) == 2 and len(red_centers) == 2:
            all_pts = green_centers + red_centers

            xs, ys = [p[0] for p in all_pts], [p[1] for p in all_pts]
            x_min, x_max = min(xs), max(xs)
            y_min, y_max = min(ys), max(ys)

            cx, cy = ((x_min + x_max) / 2) / w, ((y_min + y_max) / 2) / h
            bw, bh = (x_max - x_min) / w, (y_max - y_min) / h

            kpts_str = " ".join([f"{pt[0]/w:.6f} {pt[1]/h:.6f} 2" for pt in all_pts])

            txt_path = os.path.join(curr_lbl_dir, os.path.splitext(filename)[0] + ".txt")
            with open(txt_path, 'w', encoding='utf-8') as f:
                f.write(f"0 {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f} {kpts_str}\n")

            shutil.copy(raw_path, os.path.join(curr_img_dir, filename))

            debug_img = image.copy()
            cv2.circle(debug_img, green_centers[0], 8, (0, 255, 0), -1)
            cv2.circle(debug_img, green_centers[1], 8, (0, 255, 0), -1)
            cv2.circle(debug_img, red_centers[0], 8, (0, 0, 255), -1)
            cv2.circle(debug_img, red_centers[1], 8, (0, 0, 255), -1)
            cv2.imwrite(os.path.join(debug_dir, f"CHECK_{filename}"), debug_img)

            success_count += 1
            print(f"정밀 매칭 성공: {filename}")
        else:
            print(f"매칭 실패: {filename} (초록 점 발견 개수: {len(green_centers)}개)")

print(f"\n총 {success_count}개의 완벽한 정답 데이터가 생성되었습니다.")


# ==========================================
# 4. 기존 에러 캐시(.cache) 파일 삭제
# ==========================================
cache_files = glob.glob(f"{base_dataset_dir}/labels/*/*.cache") + glob.glob(f"{base_dataset_dir}/labels/*.cache")
for f in cache_files:
    os.remove(f)

# ==========================================
# 5. YOLO-Pose용 data.yaml 파일 생성
# ==========================================
yaml_path = os.path.join(base_dataset_dir, "data.yaml")

yaml_data = {
    'path': os.path.abspath(base_dataset_dir),
    'train': 'images/train',
    'val': 'images/val',
    'kpt_shape': [4, 3],
    'names': {0: 'box_points'}
}

with open(yaml_path, 'w', encoding='utf-8') as f:
    yaml.dump(yaml_data, f, allow_unicode=True)

# ==========================================
# 6. YOLO-Pose 학습 시작
# ==========================================
model = YOLO('yolov8s-pose.pt')
project_dir = "./runs/box_measure_pose"

results = model.train(
    data=yaml_path,
    epochs=300,
    patience=50,
    imgsz=800,
    batch=8,
    device=0,
    project=project_dir,
    name='exp_pose_high_acc',
    plots=True
)

print("\nYOLO-Pose 고정밀 모델 학습이 완료되었습니다!")

# ==========================================
# 7. 테스트 (Inference)
# ==========================================
weight_files = glob.glob(f"{project_dir}/*/weights/best.pt")
if not weight_files:
    print("학습된 모델 가중치를 찾을 수 없습니다.")
else:
    latest_model_path = max(weight_files, key=os.path.getctime)
    model = YOLO(latest_model_path)

    output_dir = "./results_inference"
    os.makedirs(output_dir, exist_ok=True)

    REAL_HINGE_MM = 153.0

    def calculate_distance(p1, p2):
        return math.sqrt((p2[0] - p1[0])**2 + (p2[1] - p1[1])**2)

    def get_dynamic_depth_ratio(raw_mm):
        if raw_mm < 130: return 1.10
        elif raw_mm < 160: return 1.15
        elif raw_mm < 180: return 1.10
        else: return 1.05

    for filename in os.listdir(val_img_dir):
        if not filename.lower().endswith((".jpg", ".png")): continue
        img_path = os.path.join(val_img_dir, filename)

        results = model.predict(source=img_path, imgsz=800, conf=0.25)

        img_array = np.fromfile(img_path, np.uint8)
        image = cv2.imdecode(img_array, cv2.IMREAD_COLOR)

        if results[0].keypoints is not None and len(results[0].keypoints.xy) > 0:
            candidates = results[0].keypoints.xy.cpu().numpy()
            chosen_kpts = None

            for kpts in candidates:
                if len(kpts) == 4:
                    box_top = kpts[2]
                    box_bottom = kpts[3]

                    x_dist = abs(box_bottom[0] - box_top[0])
                    y_dist = abs(box_bottom[1] - box_top[1])

                    if y_dist > x_dist and y_dist > 20:
                        chosen_kpts = kpts
                        break

            if chosen_kpts is not None:
                hinge_top = (int(chosen_kpts[0][0]), int(chosen_kpts[0][1]))
                hinge_bottom = (int(chosen_kpts[1][0]), int(chosen_kpts[1][1]))
                box_top = (int(chosen_kpts[2][0]), int(chosen_kpts[2][1]))
                box_bottom = (int(chosen_kpts[3][0]), int(chosen_kpts[3][1]))

                green_px_dist = calculate_distance(hinge_top, hinge_bottom)
                red_px_dist = calculate_distance(box_top, box_bottom)

                scale_factor = REAL_HINGE_MM / green_px_dist if green_px_dist > 0 else 0
                raw_box_mm = red_px_dist * scale_factor
                real_box_mm = raw_box_mm * get_dynamic_depth_ratio(raw_box_mm)

                cv2.line(image, hinge_top, hinge_bottom, (0, 255, 0), 2)
                cv2.line(image, box_top, box_bottom, (0, 0, 255), 2)

                print(f"[{filename}] 산출된 타겟: {real_box_mm:.1f} mm")
            else:
                print(f"[{filename}] 무시.")
        else:
             print(f"[{filename}] 인식 실패.")

        is_success, result_img_array = cv2.imencode(".jpg", image)
        if is_success:
            result_img_array.tofile(os.path.join(output_dir, f"AI_measured_{filename}"))