# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Lmb7SoP0XSjUULtbuVT9LLwb__3jj7x
"""

# 필요 모듈 설치
!pip install opencv-python pyserial ultralytics

import cv2
import math
import numpy as np
import serial
import time
from ultralytics import YOLO

# ==========================================
# 1. 설정 및 초기화
# ==========================================
ARDUINO_PORT = 'COM44' # 본인 포트에 맞게 수정
BAUD_RATE = 115200

try:
    py_serial = serial.Serial(port=ARDUINO_PORT, baudrate=BAUD_RATE, timeout=1)
    time.sleep(2)
    print(f"아두이노 연결 성공! ({ARDUINO_PORT})")
except Exception as e:
    print(f"아두이노 연결 실패: {e}")
    py_serial = None

model = YOLO('yolo-pose best.pt')

REAL_HINGE_MM = 153.0
LEAD_SCREW_TOTAL_MM = 400.0
STEPS_PER_MM = 25.0

def calculate_distance(p1, p2):
    return math.sqrt((p2[0] - p1[0])**2 + (p2[1] - p1[1])**2)

def get_dynamic_depth_ratio(raw_mm):
    if raw_mm < 130: return 1.10
    elif raw_mm < 160: return 1.15
    elif raw_mm < 180: return 1.10
    else: return 1.05

# ==========================================
# 2. 실시간 루프 (수동 전송 + 대기 상태 확인)
# ==========================================
cap = cv2.VideoCapture(0)
is_arduino_working = False  # 기계 작동 상태 확인용

print("\n실시간 AI 높이 측정 시작...")
print("상자를 조준하고 키보드 [ S ]를 누르면 전송됩니다.")

while True:
    ret, frame = cap.read()
    if not ret: break

    # --- 1. 아두이노가 작동 중일 때 ---
    if is_arduino_working:
        cv2.putText(frame, "Machine is moving... Please wait.", (30, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 255), 2)

        # 아두이노가 끝났다는 신호("Cycle Finished")를 보내는지 확인
        if py_serial and py_serial.in_waiting > 0:
            msg = py_serial.readline().decode('utf-8').strip()
            if "Cycle Finished" in msg:
                print("\n작업 완료! 다음 상자를 올리고 [ S ]를 누르세요.")
                is_arduino_working = False  # 다시 S키를 누를 수 있게 잠금 해제!

        cv2.imshow("Webcam AI Measure", frame)
        cv2.waitKey(1)
        continue

    # --- 2. 아두이노가 대기 중일 때 (AI 측정 및 화면 표시) ---
    results = model.predict(source=frame, imgsz=640, conf=0.25, verbose=False)

    real_box_mm = 0.0
    target_move_steps = 0
    move_mm = 0.0

    if results[0].keypoints is not None and len(results[0].keypoints.xy) > 0:
        candidates = results[0].keypoints.xy.cpu().numpy()
        chosen_kpts = None

        for kpts in candidates:
            if len(kpts) == 4:
                box_top, box_bottom = kpts[2], kpts[3]
                if abs(box_bottom[1] - box_top[1]) > abs(box_bottom[0] - box_top[0]) and abs(box_bottom[1] - box_top[1]) > 20:
                    chosen_kpts = kpts
                    break

        if chosen_kpts is not None:
            hinge_top = (int(chosen_kpts[0][0]), int(chosen_kpts[0][1]))
            hinge_bottom = (int(chosen_kpts[1][0]), int(chosen_kpts[1][1]))
            box_top = (int(chosen_kpts[2][0]), int(chosen_kpts[2][1]))
            box_bottom = (int(chosen_kpts[3][0]), int(chosen_kpts[3][1]))

            green_px_dist = calculate_distance(hinge_top, hinge_bottom)
            red_px_dist = calculate_distance(box_top, box_bottom)

            scale_factor = REAL_HINGE_MM / green_px_dist if green_px_dist > 0 else 0
            raw_box_mm = red_px_dist * scale_factor
            real_box_mm = raw_box_mm * get_dynamic_depth_ratio(raw_box_mm)

            move_mm = LEAD_SCREW_TOTAL_MM - real_box_mm
            if move_mm < 0: move_mm = 0

            target_move_steps = int(move_mm * STEPS_PER_MM)

            cv2.line(frame, hinge_top, hinge_bottom, (0, 255, 0), 2)
            cv2.line(frame, box_top, box_bottom, (0, 0, 255), 2)
            cv2.putText(frame, f"Box Height: {real_box_mm:.1f}mm", (30, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
            cv2.putText(frame, f"Target: {move_mm:.1f}mm | Press 'S' to Send", (30, 80), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 0), 2)

    cv2.imshow("Webcam AI Measure", frame)

    key = cv2.waitKey(1) & 0xFF

    # 사용자가 S를 눌렀을 때만 아두이노로 전송
    if (key == ord('s') or key == ord('S')):
        if target_move_steps > 0 and py_serial is not None:
            cmd = f"{target_move_steps}\n"
            py_serial.write(cmd.encode())
            print(f"[S키 입력됨] 전송 완료: {target_move_steps} steps")
            is_arduino_working = True  # 기계가 다 움직일 때까지 잠금!
        else:
            print("상자가 화면에 제대로 인식되지 않았거나 연결 오류입니다.")

    elif key == 27: # Esc 종료
        break

cap.release()
cv2.destroyAllWindows()
if py_serial: py_serial.close()